### ISSUE TITLE
Library is regularly down

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#51]
The monitoring of the https service tells me:
The monitor Library (https://library.kiwix.org) is currently DOWN (HTTP 502 - Bad Gateway). 

I had a brief look to the error log and it seems the limit is not configured properly.

**Comment by florentk** [comment]
@kelson42 I have increase the request/second and burst limit

**Comment by kelson42** [comment]
@florentk I still get errors, even if this seems to be a bit less. In any case there should not be any global limit, the limits should apply per IP. So we should not have any problem due to the limitation we apply per IP.

**Comment by florentk** [comment]
@kelson42 I increase the limit by IP from 10 r/s to 20 r/s

**Comment by kelson42** [comment]
@florentk I had a look a bit to that problem and I really suspect that we deal here with something else (not related to the reverse proxy). At least one problem is that we restart the kiwix-serve one time a day and that with so many ZIM files, it takes time to be again available. See https://github.com/kiwix/kiwix-tools/issues/243. So I think so far there is nothing to do. Thx for configuring/tuning the limit.

**Comment by florentk** [comment]
@kelson42 I have fixed limit in the image in #6a92598

**Comment by kelson42** [comment]
OK, we still have a problem. Every few days kiwix-serve seems to not answer anymore and the only way to recover is to restart kiwix-serve or the whole "library" Docker container.

**Comment by kelson42** [comment]
Seems to be better since 2.0.0 release :) Will close the ticket now an reopen it if necessary.
